# Generated by Django 5.0.1 on 2026-01-09 15:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('access_control', 'Access Control'), ('data_protection', 'Data Protection'), ('network_security', 'Network Security'), ('incident_response', 'Incident Response'), ('vulnerability_management', 'Vulnerability Management'), ('business_continuity', 'Business Continuity'), ('security_governance', 'Security Governance')], max_length=50)),
                ('framework', models.CharField(choices=[('nist', 'NIST CSF'), ('iso27001', 'ISO 27001'), ('soc2', 'SOC 2'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('question_text', models.TextField()),
                ('guidance', models.TextField(blank=True, help_text='Additional guidance or clarification for the question')),
                ('response_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('rating', 'Rating (1-5)'), ('text', 'Free Text')], default='yes_no', max_length=20)),
                ('response_options', models.JSONField(blank=True, default=list, help_text='Available options for multiple choice questions')),
                ('weight', models.FloatField(default=1.0, help_text='Question weight for scoring (1.0 = normal, higher = more important)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('max_score', models.IntegerField(default=100, help_text='Maximum score for this question')),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'db_table': 'assessment_questions',
                'ordering': ['category', 'order', 'question_text'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('nist', 'NIST CSF'), ('iso27001', 'ISO 27001'), ('soc2', 'SOC 2'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Template',
                'verbose_name_plural': 'Assessment Templates',
                'db_table': 'assessment_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('custom_guidance', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentquestion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttemplate')),
            ],
            options={
                'db_table': 'template_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='questions',
            field=models.ManyToManyField(related_name='templates', through='assessments.TemplateQuestion', to='assessments.assessmentquestion'),
        ),
        migrations.CreateModel(
            name='VendorAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('assessment_type', models.CharField(choices=[('initial', 'Initial Assessment'), ('annual', 'Annual Review'), ('triggered', 'Triggered Assessment'), ('incident_followup', 'Incident Follow-up')], default='initial', max_length=50)),
                ('responses', models.JSONField(default=dict, help_text='Detailed questionnaire responses')),
                ('access_control_score', models.IntegerField(default=0, help_text='Access control and authentication score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data_protection_score', models.IntegerField(default=0, help_text='Data protection and encryption score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('network_security_score', models.IntegerField(default=0, help_text='Network security and segmentation score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('incident_response_score', models.IntegerField(default=0, help_text='Incident response capabilities score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vulnerability_management_score', models.IntegerField(default=0, help_text='Vulnerability and patch management score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('business_continuity_score', models.IntegerField(default=0, help_text='Business continuity and disaster recovery score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('security_governance_score', models.IntegerField(default=0, help_text='Security governance and policies score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='General notes about the assessment')),
                ('findings', models.TextField(blank=True, help_text='Key findings and concerns')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessments', to=settings.AUTH_USER_MODEL)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Assessment',
                'verbose_name_plural': 'Vendor Assessments',
                'db_table': 'vendor_assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('screenshot', 'Screenshot'), ('certificate', 'Certificate'), ('report', 'Report'), ('other', 'Other')], default='document', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Upload supporting documentation', upload_to='assessment_evidence/')),
                ('question_id', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='assessments.vendorassessment')),
            ],
            options={
                'verbose_name': 'Assessment Evidence',
                'verbose_name_plural': 'Assessment Evidence',
                'db_table': 'assessment_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['category', 'is_active'], name='assessment__categor_4759ec_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['framework'], name='assessment__framewo_4bb63e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatequestion',
            unique_together={('template', 'question')},
        ),
        migrations.AddIndex(
            model_name='vendorassessment',
            index=models.Index(fields=['vendor', 'assessment_date'], name='vendor_asse_vendor__1b7939_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorassessment',
            index=models.Index(fields=['status'], name='vendor_asse_status_7abea1_idx'),
        ),
    ]
