# Generated by Django 5.0.1 on 2026-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organizationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='customer_base',
            field=models.IntegerField(default=10000, help_text='Estimated number of customers served by this organisation'),
        ),
    ]
