# Generated by Django 5.0.1 on 2026-04-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_customer_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
