"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv 
load_dotenv()
env_path = Path('.')/'.env'
load_dotenv(dotenv_path=env_path)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_yasg',
    'django_extensions',
    'Account',
    'core',
    'vendors',
    'assessments',
    'simulations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
        'anon': '100/day',
    },
}
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}



EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'

IS_DEVELOPMENT = DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not IS_DEVELOPMENT  
SESSION_COOKIE_SECURE = not IS_DEVELOPMENT
CSRF_COOKIE_SECURE = not IS_DEVELOPMENT
SECURE_HSTS_SECONDS = 31536000 if not IS_DEVELOPMENT else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not IS_DEVELOPMENT
SECURE_HSTS_PRELOAD = not IS_DEVELOPMENT
SECURE_BROWSER_XSS_FILTER = not IS_DEVELOPMENT
SECURE_CONTENT_TYPE_NOSNIFF = not IS_DEVELOPMENT
X_FRAME_OPTIONS = 'DENY'

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
]

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'Account.CustomUser'

SWAGGER_SETTINGS = {
    'PERSIST_AUTH': True,  
    'USE_SESSION_AUTH': False, 
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Enter your JWT token with `Bearer ` prefix, e.g. Bearer <token>',
        }
    },
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'tpvrs.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'simulations': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Simulation Engine Settings
SIMULATION_CONFIG = {
    # Cost calculations
    'PER_RECORD_BREACH_COST': 150,  # Average cost per breached record (USD)
    'GDPR_PENALTY_PER_RECORD': 4,   # GDPR penalty per record (EUR ~= USD)
    'HIPAA_PENALTY_PER_RECORD': 250, # HIPAA penalty per record (USD)
    
    # Industry-specific churn rates (percentage)
    'CHURN_RATES': {
        'technology': 0.15,
        'healthcare': 0.20,
        'financial': 0.25,
        'retail': 0.18,
        'manufacturing': 0.12,
        'professional_services': 0.14,
        'education': 0.10,
        'government': 0.08,
        'default': 0.15
    },
    
    # Recovery time multipliers by scenario type
    'RECOVERY_TIME_MULTIPLIERS': {
        'data_breach': 1.5,
        'ransomware': 2.0,
        'service_disruption': 1.2,
        'supply_chain': 3.0,
        'multi_vendor': 2.5
    },
    
    # Monte Carlo simulation settings
    'MAX_MONTE_CARLO_ITERATIONS': 10000,
    'DEFAULT_MONTE_CARLO_ITERATIONS': 1000,
    'MONTE_CARLO_VARIANCE': 0.15,  # 15% standard deviation
    
    # Cascade analysis settings
    'MAX_CASCADE_DEPTH': 5,
    'CASCADE_IMPACT_DECAY': 0.8,  # 20% reduction per level
    
    # Risk score thresholds
    'RISK_SCORE_THRESHOLDS': {
        'critical': 75,
        'high': 50,
        'medium': 25,
        'low': 0
    },
    
    # Customer lifetime value estimates (USD) by industry
    'CUSTOMER_LIFETIME_VALUES': {
        'technology': 5000,
        'healthcare': 3000,
        'financial': 8000,
        'retail': 500,
        'manufacturing': 10000,
        'professional_services': 4000,
        'default': 2000
    },
    
    # Hourly IT team rates for incident response
    'INCIDENT_RESPONSE_HOURLY_RATE': 250,
    
    # SLA breach penalty rates
    'SLA_PENALTY_RATES': {
        'minor': 0.01,   # 1% of contract value
        'moderate': 0.05,  # 5% of contract value
        'major': 0.10,    # 10% of contract value
        'critical': 0.20   # 20% of contract value
    },
    
    # Reputational damage estimates (USD)
    'REPUTATIONAL_DAMAGE': {
        'minor': 50000,
        'moderate': 200000,
        'major': 1000000,
        'severe': 5000000
    },
    
    # Regulatory notification costs
    'NOTIFICATION_COSTS': {
        'per_customer_email': 1,
        'per_customer_letter': 5,
        'per_customer_credit_monitoring': 150,
        'legal_review': 50000,
        'pr_crisis_management': 100000
    }
}