# Generated by Django 5.0.1 on 2026-01-09 15:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('services_provided', models.TextField()),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('security_posture_score', models.IntegerField(default=0, help_text='Overall security controls score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data_sensitivity_level', models.IntegerField(default=1, help_text='Data sensitivity level (1-5, 5 being most sensitive)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service_criticality_level', models.IntegerField(default=1, help_text='Service criticality level (1-5, 5 being most critical)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('incident_history_score', models.IntegerField(default=100, help_text='Historical incident score (100 = no incidents, lower = more incidents)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('compliance_score', models.IntegerField(default=0, help_text='Compliance and certification score (0-50)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('third_party_dependencies_score', models.IntegerField(default=0, help_text='Third-party dependency risk score (0-50)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('overall_risk_score', models.FloatField(default=0.0, editable=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low (0-25)'), ('medium', 'Medium (26-50)'), ('high', 'High (51-75)'), ('critical', 'Critical (76-100)')], default='medium', editable=False, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
                ('dependent_vendors', models.ManyToManyField(blank=True, help_text='Vendors this vendor depends on', related_name='dependency_of', to='vendors.vendor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.organization')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['-overall_risk_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_date', models.DateField()),
                ('incident_type', models.CharField(choices=[('data_breach', 'Data Breach'), ('ransomware', 'Ransomware'), ('ddos', 'DDoS Attack'), ('outage', 'Service Outage'), ('supply_chain', 'Supply Chain Attack'), ('insider_threat', 'Insider Threat'), ('malware', 'Malware Infection'), ('phishing', 'Phishing Attack'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('records_affected', models.IntegerField(default=0, help_text='Number of records compromised')),
                ('downtime_hours', models.FloatField(default=0, help_text='Hours of service downtime')),
                ('financial_impact', models.DecimalField(decimal_places=2, default=0, help_text='Estimated financial impact in USD', max_digits=15)),
                ('time_to_detect_hours', models.FloatField(default=0, help_text='Hours to detect the incident')),
                ('time_to_contain_hours', models.FloatField(default=0, help_text='Hours to contain the incident')),
                ('time_to_recover_hours', models.FloatField(default=0, help_text='Hours to fully recover')),
                ('root_cause', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('remediation_actions', models.TextField(blank=True)),
                ('remediation_completed', models.BooleanField(default=False)),
                ('publicly_disclosed', models.BooleanField(default=False)),
                ('disclosure_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_history', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incident History',
                'db_table': 'incident_history',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_type', models.CharField(choices=[('iso27001', 'ISO 27001'), ('iso27017', 'ISO 27017 (Cloud)'), ('iso27018', 'ISO 27018 (Privacy)'), ('soc2_type1', 'SOC 2 Type I'), ('soc2_type2', 'SOC 2 Type II'), ('pci_dss', 'PCI DSS'), ('hipaa', 'HIPAA Compliant'), ('gdpr', 'GDPR Compliant'), ('fedramp_low', 'FedRAMP Low'), ('fedramp_moderate', 'FedRAMP Moderate'), ('fedramp_high', 'FedRAMP High'), ('nist_csf', 'NIST Cybersecurity Framework'), ('cyber_essentials', 'Cyber Essentials'), ('other', 'Other')], max_length=50)),
                ('certification_body', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_file', models.FileField(blank=True, help_text='Upload certificate document', null=True, upload_to='certifications/')),
                ('verification_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certifications', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Compliance Certifications',
                'db_table': 'compliance_certifications',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('primary', 'Primary Contact'), ('technical', 'Technical Contact'), ('security', 'Security Contact'), ('billing', 'Billing Contact'), ('legal', 'Legal Contact'), ('executive', 'Executive Contact')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Contact',
                'verbose_name_plural': 'Vendor Contacts',
                'db_table': 'vendor_contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', 'risk_level'], name='vendors_organiz_055fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', 'is_active'], name='vendors_organiz_62a5e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='incidenthistory',
            index=models.Index(fields=['vendor', 'incident_date'], name='incident_hi_vendor__c467b5_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenthistory',
            index=models.Index(fields=['severity', 'incident_date'], name='incident_hi_severit_ddb91d_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecertification',
            index=models.Index(fields=['vendor', 'is_active'], name='compliance__vendor__fc326a_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecertification',
            index=models.Index(fields=['expiry_date'], name='compliance__expiry__1d3504_idx'),
        ),
    ]
