# Generated by Django 5.0.1 on 2026-01-25 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancecertification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='incidenthistory',
            name='downtime_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='incidenthistory',
            name='financial_impact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='incidenthistory',
            name='records_affected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incidenthistory',
            name='time_to_contain_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='incidenthistory',
            name='time_to_detect_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='incidenthistory',
            name='time_to_recover_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='compliance_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='data_sensitivity_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='dependent_vendors',
            field=models.ManyToManyField(blank=True, related_name='dependency_of', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='incident_history_score',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='security_posture_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='service_criticality_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='third_party_dependencies_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
