# Generated by Django 5.0.1 on 2026-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_compliancecertification_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='hourly_operating_cost',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Estimated hourly cost when vendor services are unavailable', max_digits=12),
        ),
    ]
