# Generated by Django 5.0.1 on 2026-04-17 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_hourly_operating_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='compliance_score',
            field=models.IntegerField(default=0, help_text='Compliance status score (0–50, higher = more compliant)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='third_party_dependencies_score',
            field=models.IntegerField(default=0, help_text='Third-party dependency exposure score (0–50, higher = more exposed)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
