# Generated by Django 5.0.1 on 2026-01-09 15:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_type', models.CharField(choices=[('data_breach', 'Data Breach'), ('ransomware', 'Ransomware Attack'), ('service_disruption', 'Service Disruption'), ('supply_chain', 'Supply Chain Compromise'), ('multi_vendor', 'Multi-Vendor Failure')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('default_parameters', models.JSONField(default=dict, help_text='Default parameters for this scenario type')),
                ('calculation_config', models.JSONField(default=dict, help_text='Configuration for impact calculations')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scenario Template',
                'verbose_name_plural': 'Scenario Templates',
                'db_table': 'scenario_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('criticality_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical'), (5, 'Mission Critical')], default=3, help_text='Business criticality (1-5, 5 being most critical)')),
                ('hourly_operating_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost per hour when process is down', max_digits=12)),
                ('annual_revenue_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Annual revenue contribution of this process', max_digits=15)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent_vendors', models.ManyToManyField(blank=True, related_name='supports_processes', to='vendors.vendor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_processes', to='core.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Process',
                'verbose_name_plural': 'Business Processes',
                'db_table': 'business_processes',
                'ordering': ['-criticality_level', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict, help_text='Specific parameters for this simulation run')),
                ('use_monte_carlo', models.BooleanField(default=False, help_text='Use Monte Carlo simulation for probabilistic analysis')),
                ('monte_carlo_iterations', models.IntegerField(default=1000, help_text='Number of Monte Carlo iterations (100-10000)', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_simulations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='core.organization')),
                ('scenario_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='simulations.scenariotemplate')),
                ('target_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'db_table': 'simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('comparison_data', models.JSONField(default=dict, help_text='Detailed comparison analysis results')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comparisons', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_comparisons', to='core.organization')),
                ('simulations', models.ManyToManyField(related_name='comparisons', to='simulations.simulation')),
            ],
            options={
                'verbose_name': 'Simulation Comparison',
                'verbose_name_plural': 'Simulation Comparisons',
                'db_table': 'simulation_comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direct_costs', models.DecimalField(decimal_places=2, default=0, help_text='Direct incident response and remediation costs', max_digits=15)),
                ('operational_costs', models.DecimalField(decimal_places=2, default=0, help_text='Business disruption and productivity loss costs', max_digits=15)),
                ('regulatory_costs', models.DecimalField(decimal_places=2, default=0, help_text='Fines, penalties, and legal costs', max_digits=15)),
                ('reputational_costs', models.DecimalField(decimal_places=2, default=0, help_text='Customer churn and brand damage costs', max_digits=15)),
                ('total_financial_impact', models.DecimalField(decimal_places=2, default=0, help_text='Total financial impact', max_digits=15)),
                ('downtime_hours', models.FloatField(default=0, help_text='Estimated hours of downtime')),
                ('productivity_loss_percentage', models.FloatField(default=0, help_text='Percentage of productivity loss', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('customers_affected', models.IntegerField(default=0, help_text='Number of customers potentially affected')),
                ('estimated_recovery_time_hours', models.FloatField(default=0, help_text='Estimated time to full recovery (hours)')),
                ('recovery_complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=50)),
                ('cascading_vendor_impacts', models.JSONField(default=list, help_text='List of affected vendors and their impacts')),
                ('total_cascading_impact', models.DecimalField(decimal_places=2, default=0, help_text='Total financial impact from cascading failures', max_digits=15)),
                ('monte_carlo_results', models.JSONField(blank=True, default=dict, help_text='Statistical results from Monte Carlo simulation')),
                ('impact_breakdown', models.JSONField(default=dict, help_text='Detailed breakdown of all impact calculations')),
                ('risk_score', models.FloatField(default=0, help_text='Overall risk score from simulation (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_processes', models.ManyToManyField(blank=True, related_name='impacted_by_simulations', to='simulations.businessprocess')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='simulations.simulation')),
            ],
            options={
                'verbose_name': 'Simulation Result',
                'verbose_name_plural': 'Simulation Results',
                'db_table': 'simulation_results',
            },
        ),
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('custom_parameters', models.JSONField(default=dict, help_text='Organization-specific parameter overrides')),
                ('is_default', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False, help_text='Share with other users in organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_scenarios', to='simulations.scenariotemplate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_scenarios', to='core.organization')),
            ],
            options={
                'verbose_name': 'Custom Simulation Scenario',
                'verbose_name_plural': 'Custom Simulation Scenarios',
                'db_table': 'simulation_scenarios',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['organization', 'status'], name='simulations_organiz_e44f02_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['target_vendor', 'created_at'], name='simulations_target__8003ef_idx'),
        ),
    ]
