# Generated by Django 5.0.1 on 2026-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_seed_scenario_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='customer_count',
            field=models.IntegerField(default=0, help_text='Number of customers impacted if this process fails'),
        ),
    ]
