# Generated by Django 5.0.1 on 2026-04-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_businessprocess_customer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprocess',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
